CREATE TABLE dokter (
	id_dokter SERIAL PRIMARY KEY,
	nama_dokter VARCHAR(100) NOT NULL,
	no_hp VARCHAR(20) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL.
	password VARCHAR(255) NOT NULL,
	alamat TEXT,
	klinik VARCHAR(100),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);


CREATE TABLE produk (
	id_produk SERIAL PRIMARY KEY,
	nama_bahan VARCHAR(100) NOR NULL,
	spesifikasi TEXT,
	harga NUMERIC(12,2) NOT NULL CHECK (harga>0)
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
